### ISSUE TITLE
Need a Forgot Password Functionality.

### ISSUE THREAD

**Issue by sudovishal** [sudovishal/journalling-web#2]
in the web app, while logging in, there should be a forgot password button in case the used forgets his/her password.
Same thing should be implemented in the Profile Edit Section.

**Comment by Light357** [comment]
I would like to work on your Forget Password Function.

**Comment by Light357** [comment]
thank you, i ll give my best on it.

**Comment by vish-shinde** [comment]
@Light357 You have to work on ```password-reset.js```, ```sendEmail.js``` from the routes directory and ```password-reset.ejs``` , and ```requestResetPassword.ejs``` from views directory.
I have done few small changes. after you cloned the repo, please clone again. they arent big changes though.

**Comment by sudovishal** [comment]
Done on the master branch.
